services:
  app:
    build: .
    restart: always
    environment:
      - BOT_TOKEN=
      - OWNER_ID=724477101
      - DATABASE_HOST=mongodb
      - DATABASE_NAME=TemplateBot
  mongodb:
    image: mongo
    restart: always
    volumes:
      - mongodb:/data/db

volumes:
  mongodb: