services:
  app:
    build: .
    environment:
    - BOT_TOKEN=
    - OWNER_ID=724477101
    - DATABASE_HOST=mongodb
    - DATABASE_NAME=TemplateBot
    restart: always
  mongodb:
    image: mongo
    restart: always
    volumes:
    - mongodb:/data/db
volumes:
  mongodb: null
